version: '3.8'

services:
  discord-bot-forge:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discord-bot-forge
    restart: unless-stopped
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - BOT_OWNER_ID=${BOT_OWNER_ID}
      - DEBUG=${DEBUG:-false}
      - WEB_PORT=8080
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  discord-bot-network:
    driver: bridge
